/**
 * postgres.js
 * 
 * Archivo de configuración y conexión a PostgreSQL.
 * Crea un pool de conexiones con la base de datos PostgreSQL
 * y maneja la conexión y errores automáticamente.
 */

import pg from 'pg';
import { env } from './env.js';

const { Pool } = pg;

export const pool = new Pool({
  connectionString: env.postgresUri
});

pool.connect()
  .then(() => console.log("PostgreSQL connected"))
  .catch(err => console.error("PostgreSQL error:", err));



export async function createTables() {
	const client = await pool.connect();
	try {
		// Iniciar transacción para garantizar atomicidad
		await client.query("BEGIN");

    await client.query(`
    CREATE TABLE IF NOT EXISTS "customer" (
      "id" INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      "customer_name" VARCHAR(100) NOT NULL,
      "customer_email" VARCHAR(100) NOT NULL UNIQUE,
      "customer_address" VARCHAR(100) NOT NULL,
      "customer_phone" VARCHAR(120) NOT NULL
    );`);

     await client.query(`
    CREATE TABLE IF NOT EXISTS "supplier" (
    "id" INTEGER NOT NULL UNIQUE PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "supplier_name" VARCHAR(100) NOT NULL,
    "supplier_email" VARCHAR(255) NOT NULL UNIQUE
  );`);

    

    await client.query(`CREATE TABLE IF NOT EXISTS "category" (
	"id" INTEGER NOT NULL UNIQUE PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"category_name" VARCHAR(100) NOT NULL
);`);


    await client.query(`CREATE TABLE IF NOT EXISTS "product" (
      "id" INTEGER NOT NULL UNIQUE PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      "product_name" VARCHAR(100) NOT NULL UNIQUE,
      "unit_price" NUMERIC(10,2) NOT NULL,
      "id_categoria" INTEGER NOT NULL,
      "id_proveedor" INTEGER NOT NULL,
      FOREIGN KEY("id_categoria") REFERENCES "category"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
      FOREIGN KEY("id_proveedor") REFERENCES "supplier"("id") ON UPDATE NO ACTION ON DELETE NO ACTION
    );`); 

 

    await client.query(`CREATE TABLE IF NOT EXISTS "detail_transaction" (
	"id" INTEGER NOT NULL UNIQUE PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"sku" VARCHAR(255) NOT NULL,
	"quantity" VARCHAR(100) NOT NULL,
	"total_line_value" NUMERIC NOT NULL
);
`);

    await client.query(`CREATE TABLE IF NOT EXISTS "transaction" (
    "transaction_id" INTEGER NOT NULL UNIQUE PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_customer" INTEGER NOT NULL,
    "id_product" INTEGER NOT NULL,
    "id_supplier" INTEGER NOT NULL,
    "id_detail" INTEGER NOT NULL,
    "date" DATE NOT NULL,
    FOREIGN KEY("id_customer") REFERENCES "customer"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY("id_product") REFERENCES "product"("id") ON UPDATE NO ACTION ON DELETE NO ACTION, 
    FOREIGN KEY("id_supplier") REFERENCES "supplier"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY("id_detail") REFERENCES "detail_transaction"("id") ON UPDATE NO ACTION ON DELETE NO ACTION
  );`);

    
await client.query(`CREATE INDEX IF NOT EXISTS idx_transaction_customer ON "transaction" (id_customer)`);
    await client.query(`CREATE INDEX IF NOT EXISTS idx_transaction_product ON "transaction" (id_product)`);
    await client.query(`CREATE INDEX IF NOT EXISTS idx_transaction_supplier ON "transaction" (id_supplier)`);


		await client.query("COMMIT");
		console.log("Tables created successfully");

	} catch (error) {
		console.error("Error creating tables", error);
		await client.query("ROLLBACK");
	} finally {
		client.release();
	}
	}